// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.12.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -1210377952;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__enrollment__analyze_enrollment_clip_16k_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "analyze_enrollment_clip_16k",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_samples = <Vec<i16>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(
                        crate::api::enrollment::analyze_enrollment_clip_16k(api_samples),
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__enrollment__analyze_enrollment_clip_16k_tuned_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "analyze_enrollment_clip_16k_tuned",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_samples = <Vec<i16>>::sse_decode(&mut deserializer);
            let api_min_duration_ms = <u32>::sse_decode(&mut deserializer);
            let api_max_duration_ms = <u32>::sse_decode(&mut deserializer);
            let api_min_snr_db = <f32>::sse_decode(&mut deserializer);
            let api_min_active_ratio = <f32>::sse_decode(&mut deserializer);
            let api_max_clipping_ratio = <f32>::sse_decode(&mut deserializer);
            let api_min_peak_dbfs = <f32>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(
                        crate::api::enrollment::analyze_enrollment_clip_16k_tuned(
                            api_samples,
                            api_min_duration_ms,
                            api_max_duration_ms,
                            api_min_snr_db,
                            api_min_active_ratio,
                            api_max_clipping_ratio,
                            api_min_peak_dbfs,
                        ),
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__session__append_imu_sample_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "append_imu_sample",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_ts_ns = <u64>::sse_decode(&mut deserializer);
            let api_ax = <f32>::sse_decode(&mut deserializer);
            let api_ay = <f32>::sse_decode(&mut deserializer);
            let api_az = <f32>::sse_decode(&mut deserializer);
            let api_gx = <f32>::sse_decode(&mut deserializer);
            let api_gy = <f32>::sse_decode(&mut deserializer);
            let api_gz = <f32>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::session::append_imu_sample(
                            api_ts_ns, api_ax, api_ay, api_az, api_gx, api_gy, api_gz,
                        );
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__enrollment__enroll_recorder_start_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "enroll_recorder_start",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_max_duration_ms = <u32>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::enrollment::enroll_recorder_start(api_max_duration_ms);
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__enrollment__enroll_recorder_stop_take_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "enroll_recorder_stop_take",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(crate::api::enrollment::enroll_recorder_stop_take())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__dsp_pipeline__next_dsp_event_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "next_dsp_event",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::dsp_pipeline::next_dsp_event())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__audio_stream__next_waveform_frame_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "next_waveform_frame",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok =
                    Result::<_, ()>::Ok(crate::api::audio_stream::next_waveform_frame())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__audio_stream__ring_occupancy_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "ring_occupancy",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::audio_stream::ring_occupancy())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__dsp_pipeline__start_dsp_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "start_dsp",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, String>((move || {
                let output_ok = crate::api::dsp_pipeline::start_dsp()?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__session__start_session_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "start_session",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_documents_dir = <String>::sse_decode(&mut deserializer);
            let api_ts_label = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, String>((move || {
                let output_ok =
                    crate::api::session::start_session(api_documents_dir, api_ts_label)?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__dsp_pipeline__stop_dsp_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "stop_dsp",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok({
                    crate::api::dsp_pipeline::stop_dsp();
                })?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__session__stop_session_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "stop_session",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, String>((move || {
                let output_ok = crate::api::session::stop_session()?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__dsp_pipeline__take_event_audio_16k_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "take_event_audio_16k",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_event_id = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(
                    crate::api::dsp_pipeline::take_event_audio_16k(api_event_id),
                )?;
                Ok(output_ok)
            })())
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::dsp_pipeline::DspEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_eventId = <u64>::sse_decode(deserializer);
        let mut var_timestampMs = <u64>::sse_decode(deserializer);
        let mut var_kind = <crate::api::dsp_pipeline::DspEventKind>::sse_decode(deserializer);
        let mut var_mfcc = <Vec<f32>>::sse_decode(deserializer);
        let mut var_spectralCentroidHz = <f32>::sse_decode(deserializer);
        let mut var_spectralRolloffHz = <f32>::sse_decode(deserializer);
        let mut var_spectralFlatness = <f32>::sse_decode(deserializer);
        let mut var_subBandEnergy = <Vec<f32>>::sse_decode(deserializer);
        let mut var_rms = <f32>::sse_decode(deserializer);
        let mut var_crestFactor = <f32>::sse_decode(deserializer);
        let mut var_zone = <crate::api::dsp_pipeline::Zone>::sse_decode(deserializer);
        let mut var_angleDeg = <f32>::sse_decode(deserializer);
        let mut var_spatialConfidence = <f32>::sse_decode(deserializer);
        return crate::api::dsp_pipeline::DspEvent {
            event_id: var_eventId,
            timestamp_ms: var_timestampMs,
            kind: var_kind,
            mfcc: var_mfcc,
            spectral_centroid_hz: var_spectralCentroidHz,
            spectral_rolloff_hz: var_spectralRolloffHz,
            spectral_flatness: var_spectralFlatness,
            sub_band_energy: var_subBandEnergy,
            rms: var_rms,
            crest_factor: var_crestFactor,
            zone: var_zone,
            angle_deg: var_angleDeg,
            spatial_confidence: var_spatialConfidence,
        };
    }
}

impl SseDecode for crate::api::dsp_pipeline::DspEventKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::dsp_pipeline::DspEventKind::VadStart,
            1 => crate::api::dsp_pipeline::DspEventKind::VadEnd,
            2 => crate::api::dsp_pipeline::DspEventKind::Onset,
            3 => crate::api::dsp_pipeline::DspEventKind::PeriodicSnapshot,
            _ => unreachable!("Invalid variant for DspEventKind: {}", inner),
        };
    }
}

impl SseDecode for crate::api::enrollment::EnrollClipReport {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_accepted = <bool>::sse_decode(deserializer);
        let mut var_rejectReason =
            <Option<crate::api::enrollment::EnrollRejectReason>>::sse_decode(deserializer);
        let mut var_durationMs = <u32>::sse_decode(deserializer);
        let mut var_peakDbfs = <f32>::sse_decode(deserializer);
        let mut var_rmsDbfs = <f32>::sse_decode(deserializer);
        let mut var_noiseFloorDbfs = <f32>::sse_decode(deserializer);
        let mut var_snrDb = <f32>::sse_decode(deserializer);
        let mut var_activeRatio = <f32>::sse_decode(deserializer);
        let mut var_clippingRatio = <f32>::sse_decode(deserializer);
        let mut var_zcr = <f32>::sse_decode(deserializer);
        return crate::api::enrollment::EnrollClipReport {
            accepted: var_accepted,
            reject_reason: var_rejectReason,
            duration_ms: var_durationMs,
            peak_dbfs: var_peakDbfs,
            rms_dbfs: var_rmsDbfs,
            noise_floor_dbfs: var_noiseFloorDbfs,
            snr_db: var_snrDb,
            active_ratio: var_activeRatio,
            clipping_ratio: var_clippingRatio,
            zcr: var_zcr,
        };
    }
}

impl SseDecode for crate::api::enrollment::EnrollRejectReason {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::enrollment::EnrollRejectReason::TooShort,
            1 => crate::api::enrollment::EnrollRejectReason::TooLong,
            2 => crate::api::enrollment::EnrollRejectReason::TooQuiet,
            3 => crate::api::enrollment::EnrollRejectReason::TooNoisy,
            4 => crate::api::enrollment::EnrollRejectReason::Clipping,
            5 => crate::api::enrollment::EnrollRejectReason::NoSignal,
            _ => unreachable!("Invalid variant for EnrollRejectReason: {}", inner),
        };
    }
}

impl SseDecode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i16 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i16::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<f32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<f32>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<i16> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<i16>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<crate::api::dsp_pipeline::DspEvent> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::dsp_pipeline::DspEvent>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::enrollment::EnrollRejectReason> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::enrollment::EnrollRejectReason>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::audio_stream::WaveformFrame> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::audio_stream::WaveformFrame>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::session::SessionPaths {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_wavPath = <String>::sse_decode(deserializer);
        let mut var_imuPath = <String>::sse_decode(deserializer);
        return crate::api::session::SessionPaths {
            wav_path: var_wavPath,
            imu_path: var_imuPath,
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for crate::api::audio_stream::WaveformFrame {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_timestampMs = <u64>::sse_decode(deserializer);
        let mut var_left = <Vec<i16>>::sse_decode(deserializer);
        let mut var_right = <Vec<i16>>::sse_decode(deserializer);
        let mut var_peak = <i16>::sse_decode(deserializer);
        let mut var_ringOccupancy = <u32>::sse_decode(deserializer);
        return crate::api::audio_stream::WaveformFrame {
            timestamp_ms: var_timestampMs,
            left: var_left,
            right: var_right,
            peak: var_peak,
            ring_occupancy: var_ringOccupancy,
        };
    }
}

impl SseDecode for crate::api::dsp_pipeline::Zone {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::dsp_pipeline::Zone::Left,
            1 => crate::api::dsp_pipeline::Zone::Center,
            2 => crate::api::dsp_pipeline::Zone::Right,
            3 => crate::api::dsp_pipeline::Zone::Unknown,
            _ => unreachable!("Invalid variant for Zone: {}", inner),
        };
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__enrollment__analyze_enrollment_clip_16k_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        2 => wire__crate__api__enrollment__analyze_enrollment_clip_16k_tuned_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        3 => wire__crate__api__session__append_imu_sample_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__crate__api__enrollment__enroll_recorder_start_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        5 => wire__crate__api__enrollment__enroll_recorder_stop_take_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        6 => wire__crate__api__dsp_pipeline__next_dsp_event_impl(ptr, rust_vec_len, data_len),
        7 => wire__crate__api__audio_stream__next_waveform_frame_impl(ptr, rust_vec_len, data_len),
        8 => wire__crate__api__audio_stream__ring_occupancy_impl(ptr, rust_vec_len, data_len),
        9 => wire__crate__api__dsp_pipeline__start_dsp_impl(ptr, rust_vec_len, data_len),
        10 => wire__crate__api__session__start_session_impl(ptr, rust_vec_len, data_len),
        11 => wire__crate__api__dsp_pipeline__stop_dsp_impl(ptr, rust_vec_len, data_len),
        12 => wire__crate__api__session__stop_session_impl(ptr, rust_vec_len, data_len),
        13 => {
            wire__crate__api__dsp_pipeline__take_event_audio_16k_impl(ptr, rust_vec_len, data_len)
        }
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::dsp_pipeline::DspEvent {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.event_id.into_into_dart().into_dart(),
            self.timestamp_ms.into_into_dart().into_dart(),
            self.kind.into_into_dart().into_dart(),
            self.mfcc.into_into_dart().into_dart(),
            self.spectral_centroid_hz.into_into_dart().into_dart(),
            self.spectral_rolloff_hz.into_into_dart().into_dart(),
            self.spectral_flatness.into_into_dart().into_dart(),
            self.sub_band_energy.into_into_dart().into_dart(),
            self.rms.into_into_dart().into_dart(),
            self.crest_factor.into_into_dart().into_dart(),
            self.zone.into_into_dart().into_dart(),
            self.angle_deg.into_into_dart().into_dart(),
            self.spatial_confidence.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::dsp_pipeline::DspEvent
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::dsp_pipeline::DspEvent>
    for crate::api::dsp_pipeline::DspEvent
{
    fn into_into_dart(self) -> crate::api::dsp_pipeline::DspEvent {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::dsp_pipeline::DspEventKind {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::VadStart => 0.into_dart(),
            Self::VadEnd => 1.into_dart(),
            Self::Onset => 2.into_dart(),
            Self::PeriodicSnapshot => 3.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::dsp_pipeline::DspEventKind
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::dsp_pipeline::DspEventKind>
    for crate::api::dsp_pipeline::DspEventKind
{
    fn into_into_dart(self) -> crate::api::dsp_pipeline::DspEventKind {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::enrollment::EnrollClipReport {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.accepted.into_into_dart().into_dart(),
            self.reject_reason.into_into_dart().into_dart(),
            self.duration_ms.into_into_dart().into_dart(),
            self.peak_dbfs.into_into_dart().into_dart(),
            self.rms_dbfs.into_into_dart().into_dart(),
            self.noise_floor_dbfs.into_into_dart().into_dart(),
            self.snr_db.into_into_dart().into_dart(),
            self.active_ratio.into_into_dart().into_dart(),
            self.clipping_ratio.into_into_dart().into_dart(),
            self.zcr.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::enrollment::EnrollClipReport
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::enrollment::EnrollClipReport>
    for crate::api::enrollment::EnrollClipReport
{
    fn into_into_dart(self) -> crate::api::enrollment::EnrollClipReport {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::enrollment::EnrollRejectReason {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::TooShort => 0.into_dart(),
            Self::TooLong => 1.into_dart(),
            Self::TooQuiet => 2.into_dart(),
            Self::TooNoisy => 3.into_dart(),
            Self::Clipping => 4.into_dart(),
            Self::NoSignal => 5.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::enrollment::EnrollRejectReason
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::enrollment::EnrollRejectReason>
    for crate::api::enrollment::EnrollRejectReason
{
    fn into_into_dart(self) -> crate::api::enrollment::EnrollRejectReason {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::session::SessionPaths {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.wav_path.into_into_dart().into_dart(),
            self.imu_path.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::session::SessionPaths
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::session::SessionPaths>
    for crate::api::session::SessionPaths
{
    fn into_into_dart(self) -> crate::api::session::SessionPaths {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::audio_stream::WaveformFrame {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.timestamp_ms.into_into_dart().into_dart(),
            self.left.into_into_dart().into_dart(),
            self.right.into_into_dart().into_dart(),
            self.peak.into_into_dart().into_dart(),
            self.ring_occupancy.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::audio_stream::WaveformFrame
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::audio_stream::WaveformFrame>
    for crate::api::audio_stream::WaveformFrame
{
    fn into_into_dart(self) -> crate::api::audio_stream::WaveformFrame {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::dsp_pipeline::Zone {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Left => 0.into_dart(),
            Self::Center => 1.into_dart(),
            Self::Right => 2.into_dart(),
            Self::Unknown => 3.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::dsp_pipeline::Zone
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::dsp_pipeline::Zone>
    for crate::api::dsp_pipeline::Zone
{
    fn into_into_dart(self) -> crate::api::dsp_pipeline::Zone {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::dsp_pipeline::DspEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.event_id, serializer);
        <u64>::sse_encode(self.timestamp_ms, serializer);
        <crate::api::dsp_pipeline::DspEventKind>::sse_encode(self.kind, serializer);
        <Vec<f32>>::sse_encode(self.mfcc, serializer);
        <f32>::sse_encode(self.spectral_centroid_hz, serializer);
        <f32>::sse_encode(self.spectral_rolloff_hz, serializer);
        <f32>::sse_encode(self.spectral_flatness, serializer);
        <Vec<f32>>::sse_encode(self.sub_band_energy, serializer);
        <f32>::sse_encode(self.rms, serializer);
        <f32>::sse_encode(self.crest_factor, serializer);
        <crate::api::dsp_pipeline::Zone>::sse_encode(self.zone, serializer);
        <f32>::sse_encode(self.angle_deg, serializer);
        <f32>::sse_encode(self.spatial_confidence, serializer);
    }
}

impl SseEncode for crate::api::dsp_pipeline::DspEventKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::dsp_pipeline::DspEventKind::VadStart => 0,
                crate::api::dsp_pipeline::DspEventKind::VadEnd => 1,
                crate::api::dsp_pipeline::DspEventKind::Onset => 2,
                crate::api::dsp_pipeline::DspEventKind::PeriodicSnapshot => 3,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::enrollment::EnrollClipReport {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.accepted, serializer);
        <Option<crate::api::enrollment::EnrollRejectReason>>::sse_encode(
            self.reject_reason,
            serializer,
        );
        <u32>::sse_encode(self.duration_ms, serializer);
        <f32>::sse_encode(self.peak_dbfs, serializer);
        <f32>::sse_encode(self.rms_dbfs, serializer);
        <f32>::sse_encode(self.noise_floor_dbfs, serializer);
        <f32>::sse_encode(self.snr_db, serializer);
        <f32>::sse_encode(self.active_ratio, serializer);
        <f32>::sse_encode(self.clipping_ratio, serializer);
        <f32>::sse_encode(self.zcr, serializer);
    }
}

impl SseEncode for crate::api::enrollment::EnrollRejectReason {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::enrollment::EnrollRejectReason::TooShort => 0,
                crate::api::enrollment::EnrollRejectReason::TooLong => 1,
                crate::api::enrollment::EnrollRejectReason::TooQuiet => 2,
                crate::api::enrollment::EnrollRejectReason::TooNoisy => 3,
                crate::api::enrollment::EnrollRejectReason::Clipping => 4,
                crate::api::enrollment::EnrollRejectReason::NoSignal => 5,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i16 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i16::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<f32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <f32>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<i16> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <i16>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::dsp_pipeline::DspEvent> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::dsp_pipeline::DspEvent>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::enrollment::EnrollRejectReason> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::enrollment::EnrollRejectReason>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::audio_stream::WaveformFrame> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::audio_stream::WaveformFrame>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::session::SessionPaths {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.wav_path, serializer);
        <String>::sse_encode(self.imu_path, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for crate::api::audio_stream::WaveformFrame {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.timestamp_ms, serializer);
        <Vec<i16>>::sse_encode(self.left, serializer);
        <Vec<i16>>::sse_encode(self.right, serializer);
        <i16>::sse_encode(self.peak, serializer);
        <u32>::sse_encode(self.ring_occupancy, serializer);
    }
}

impl SseEncode for crate::api::dsp_pipeline::Zone {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::dsp_pipeline::Zone::Left => 0,
                crate::api::dsp_pipeline::Zone::Center => 1,
                crate::api::dsp_pipeline::Zone::Right => 2,
                crate::api::dsp_pipeline::Zone::Unknown => 3,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
