// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/audio_stream.dart';
import 'api/dsp_pipeline.dart';
import 'api/enrollment.dart';
import 'api/session.dart';
import 'api/zone.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1147572069;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'prism_dsp',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<EnrollClipReport> crateApiEnrollmentAnalyzeEnrollmentClip16K({
    required List<int> samples,
  });

  Future<EnrollClipReport> crateApiEnrollmentAnalyzeEnrollmentClip16KTuned({
    required List<int> samples,
    required int minDurationMs,
    required int maxDurationMs,
    required double minSnrDb,
    required double minActiveRatio,
    required double maxClippingRatio,
    required double minPeakDbfs,
  });

  Future<void> crateApiSessionAppendImuSample({
    required BigInt tsNs,
    required double ax,
    required double ay,
    required double az,
    required double gx,
    required double gy,
    required double gz,
  });

  Future<void> crateApiEnrollmentEnrollRecorderStart({
    required int maxDurationMs,
  });

  Future<Int16List> crateApiEnrollmentEnrollRecorderStopTake();

  DspEvent? crateApiDspPipelineNextDspEvent();

  WaveformFrame? crateApiAudioStreamNextWaveformFrame();

  int crateApiAudioStreamRingOccupancy();

  void crateApiDspPipelineStartDsp();

  SessionPaths crateApiSessionStartSession({
    required String documentsDir,
    required String tsLabel,
  });

  void crateApiDspPipelineStopDsp();

  SessionPaths crateApiSessionStopSession();

  Int16List crateApiDspPipelineTakeEventAudio16K({required BigInt eventId});

  Float32List crateApiZoneZoneCentroidFromFeatures({
    required List<Float32List> features,
  });

  void crateApiZoneZoneClearPrototypes();

  Float32List crateApiZoneZoneComputeFeature({
    required List<int> samples16KMono,
  });

  int crateApiZoneZoneFeatureDim();

  int crateApiZoneZonePrototypeCount();

  int crateApiZoneZoneSetPrototypes({required List<ZonePrototypeDto> items});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<EnrollClipReport> crateApiEnrollmentAnalyzeEnrollmentClip16K({
    required List<int> samples,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_i_16_loose(samples, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_enroll_clip_report,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEnrollmentAnalyzeEnrollmentClip16KConstMeta,
        argValues: [samples],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEnrollmentAnalyzeEnrollmentClip16KConstMeta =>
      const TaskConstMeta(
        debugName: "analyze_enrollment_clip_16k",
        argNames: ["samples"],
      );

  @override
  Future<EnrollClipReport> crateApiEnrollmentAnalyzeEnrollmentClip16KTuned({
    required List<int> samples,
    required int minDurationMs,
    required int maxDurationMs,
    required double minSnrDb,
    required double minActiveRatio,
    required double maxClippingRatio,
    required double minPeakDbfs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_i_16_loose(samples, serializer);
          sse_encode_u_32(minDurationMs, serializer);
          sse_encode_u_32(maxDurationMs, serializer);
          sse_encode_f_32(minSnrDb, serializer);
          sse_encode_f_32(minActiveRatio, serializer);
          sse_encode_f_32(maxClippingRatio, serializer);
          sse_encode_f_32(minPeakDbfs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_enroll_clip_report,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEnrollmentAnalyzeEnrollmentClip16KTunedConstMeta,
        argValues: [
          samples,
          minDurationMs,
          maxDurationMs,
          minSnrDb,
          minActiveRatio,
          maxClippingRatio,
          minPeakDbfs,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEnrollmentAnalyzeEnrollmentClip16KTunedConstMeta =>
      const TaskConstMeta(
        debugName: "analyze_enrollment_clip_16k_tuned",
        argNames: [
          "samples",
          "minDurationMs",
          "maxDurationMs",
          "minSnrDb",
          "minActiveRatio",
          "maxClippingRatio",
          "minPeakDbfs",
        ],
      );

  @override
  Future<void> crateApiSessionAppendImuSample({
    required BigInt tsNs,
    required double ax,
    required double ay,
    required double az,
    required double gx,
    required double gy,
    required double gz,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(tsNs, serializer);
          sse_encode_f_32(ax, serializer);
          sse_encode_f_32(ay, serializer);
          sse_encode_f_32(az, serializer);
          sse_encode_f_32(gx, serializer);
          sse_encode_f_32(gy, serializer);
          sse_encode_f_32(gz, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSessionAppendImuSampleConstMeta,
        argValues: [tsNs, ax, ay, az, gx, gy, gz],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionAppendImuSampleConstMeta =>
      const TaskConstMeta(
        debugName: "append_imu_sample",
        argNames: ["tsNs", "ax", "ay", "az", "gx", "gy", "gz"],
      );

  @override
  Future<void> crateApiEnrollmentEnrollRecorderStart({
    required int maxDurationMs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(maxDurationMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEnrollmentEnrollRecorderStartConstMeta,
        argValues: [maxDurationMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEnrollmentEnrollRecorderStartConstMeta =>
      const TaskConstMeta(
        debugName: "enroll_recorder_start",
        argNames: ["maxDurationMs"],
      );

  @override
  Future<Int16List> crateApiEnrollmentEnrollRecorderStopTake() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_i_16_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEnrollmentEnrollRecorderStopTakeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEnrollmentEnrollRecorderStopTakeConstMeta =>
      const TaskConstMeta(debugName: "enroll_recorder_stop_take", argNames: []);

  @override
  DspEvent? crateApiDspPipelineNextDspEvent() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_dsp_event,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDspPipelineNextDspEventConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDspPipelineNextDspEventConstMeta =>
      const TaskConstMeta(debugName: "next_dsp_event", argNames: []);

  @override
  WaveformFrame? crateApiAudioStreamNextWaveformFrame() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_waveform_frame,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioStreamNextWaveformFrameConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioStreamNextWaveformFrameConstMeta =>
      const TaskConstMeta(debugName: "next_waveform_frame", argNames: []);

  @override
  int crateApiAudioStreamRingOccupancy() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioStreamRingOccupancyConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioStreamRingOccupancyConstMeta =>
      const TaskConstMeta(debugName: "ring_occupancy", argNames: []);

  @override
  void crateApiDspPipelineStartDsp() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDspPipelineStartDspConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDspPipelineStartDspConstMeta =>
      const TaskConstMeta(debugName: "start_dsp", argNames: []);

  @override
  SessionPaths crateApiSessionStartSession({
    required String documentsDir,
    required String tsLabel,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(documentsDir, serializer);
          sse_encode_String(tsLabel, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_session_paths,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSessionStartSessionConstMeta,
        argValues: [documentsDir, tsLabel],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionStartSessionConstMeta =>
      const TaskConstMeta(
        debugName: "start_session",
        argNames: ["documentsDir", "tsLabel"],
      );

  @override
  void crateApiDspPipelineStopDsp() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDspPipelineStopDspConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDspPipelineStopDspConstMeta =>
      const TaskConstMeta(debugName: "stop_dsp", argNames: []);

  @override
  SessionPaths crateApiSessionStopSession() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_session_paths,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSessionStopSessionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionStopSessionConstMeta =>
      const TaskConstMeta(debugName: "stop_session", argNames: []);

  @override
  Int16List crateApiDspPipelineTakeEventAudio16K({required BigInt eventId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(eventId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_i_16_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDspPipelineTakeEventAudio16KConstMeta,
        argValues: [eventId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDspPipelineTakeEventAudio16KConstMeta =>
      const TaskConstMeta(
        debugName: "take_event_audio_16k",
        argNames: ["eventId"],
      );

  @override
  Float32List crateApiZoneZoneCentroidFromFeatures({
    required List<Float32List> features,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_list_prim_f_32_strict(features, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_32_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiZoneZoneCentroidFromFeaturesConstMeta,
        argValues: [features],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZoneZoneCentroidFromFeaturesConstMeta =>
      const TaskConstMeta(
        debugName: "zone_centroid_from_features",
        argNames: ["features"],
      );

  @override
  void crateApiZoneZoneClearPrototypes() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiZoneZoneClearPrototypesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZoneZoneClearPrototypesConstMeta =>
      const TaskConstMeta(debugName: "zone_clear_prototypes", argNames: []);

  @override
  Float32List crateApiZoneZoneComputeFeature({
    required List<int> samples16KMono,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_i_16_loose(samples16KMono, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_32_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiZoneZoneComputeFeatureConstMeta,
        argValues: [samples16KMono],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZoneZoneComputeFeatureConstMeta =>
      const TaskConstMeta(
        debugName: "zone_compute_feature",
        argNames: ["samples16KMono"],
      );

  @override
  int crateApiZoneZoneFeatureDim() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiZoneZoneFeatureDimConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZoneZoneFeatureDimConstMeta =>
      const TaskConstMeta(debugName: "zone_feature_dim", argNames: []);

  @override
  int crateApiZoneZonePrototypeCount() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiZoneZonePrototypeCountConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZoneZonePrototypeCountConstMeta =>
      const TaskConstMeta(debugName: "zone_prototype_count", argNames: []);

  @override
  int crateApiZoneZoneSetPrototypes({required List<ZonePrototypeDto> items}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_zone_prototype_dto(items, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiZoneZoneSetPrototypesConstMeta,
        argValues: [items],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZoneZoneSetPrototypesConstMeta =>
      const TaskConstMeta(
        debugName: "zone_set_prototypes",
        argNames: ["items"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DspEvent dco_decode_box_autoadd_dsp_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_dsp_event(raw);
  }

  @protected
  EnrollRejectReason dco_decode_box_autoadd_enroll_reject_reason(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_enroll_reject_reason(raw);
  }

  @protected
  WaveformFrame dco_decode_box_autoadd_waveform_frame(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_waveform_frame(raw);
  }

  @protected
  DspEvent dco_decode_dsp_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 18)
      throw Exception('unexpected arr length: expect 18 but see ${arr.length}');
    return DspEvent(
      eventId: dco_decode_u_64(arr[0]),
      timestampMs: dco_decode_u_64(arr[1]),
      kind: dco_decode_dsp_event_kind(arr[2]),
      mfcc: dco_decode_list_prim_f_32_strict(arr[3]),
      spectralCentroidHz: dco_decode_f_32(arr[4]),
      spectralRolloffHz: dco_decode_f_32(arr[5]),
      spectralFlatness: dco_decode_f_32(arr[6]),
      subBandEnergy: dco_decode_list_prim_f_32_strict(arr[7]),
      rms: dco_decode_f_32(arr[8]),
      crestFactor: dco_decode_f_32(arr[9]),
      zone: dco_decode_zone(arr[10]),
      angleDeg: dco_decode_f_32(arr[11]),
      spatialConfidence: dco_decode_f_32(arr[12]),
      smoothedAngleDeg: dco_decode_f_32(arr[13]),
      smoothedAngleConfidence: dco_decode_f_32(arr[14]),
      zoneLabel: dco_decode_String(arr[15]),
      zoneId: dco_decode_String(arr[16]),
      zoneConfidence: dco_decode_f_32(arr[17]),
    );
  }

  @protected
  DspEventKind dco_decode_dsp_event_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DspEventKind.values[raw as int];
  }

  @protected
  EnrollClipReport dco_decode_enroll_clip_report(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return EnrollClipReport(
      accepted: dco_decode_bool(arr[0]),
      rejectReason: dco_decode_opt_box_autoadd_enroll_reject_reason(arr[1]),
      durationMs: dco_decode_u_32(arr[2]),
      peakDbfs: dco_decode_f_32(arr[3]),
      rmsDbfs: dco_decode_f_32(arr[4]),
      noiseFloorDbfs: dco_decode_f_32(arr[5]),
      snrDb: dco_decode_f_32(arr[6]),
      activeRatio: dco_decode_f_32(arr[7]),
      clippingRatio: dco_decode_f_32(arr[8]),
      zcr: dco_decode_f_32(arr[9]),
    );
  }

  @protected
  EnrollRejectReason dco_decode_enroll_reject_reason(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return EnrollRejectReason.values[raw as int];
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<Float32List> dco_decode_list_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_list_prim_f_32_strict)
        .toList();
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  List<int> dco_decode_list_prim_i_16_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Int16List dco_decode_list_prim_i_16_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Int16List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ZonePrototypeDto> dco_decode_list_zone_prototype_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_zone_prototype_dto).toList();
  }

  @protected
  DspEvent? dco_decode_opt_box_autoadd_dsp_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_dsp_event(raw);
  }

  @protected
  EnrollRejectReason? dco_decode_opt_box_autoadd_enroll_reject_reason(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_enroll_reject_reason(raw);
  }

  @protected
  WaveformFrame? dco_decode_opt_box_autoadd_waveform_frame(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_waveform_frame(raw);
  }

  @protected
  SessionPaths dco_decode_session_paths(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SessionPaths(
      wavPath: dco_decode_String(arr[0]),
      imuPath: dco_decode_String(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  WaveformFrame dco_decode_waveform_frame(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return WaveformFrame(
      timestampMs: dco_decode_u_64(arr[0]),
      left: dco_decode_list_prim_i_16_strict(arr[1]),
      right: dco_decode_list_prim_i_16_strict(arr[2]),
      peak: dco_decode_i_16(arr[3]),
      ringOccupancy: dco_decode_u_32(arr[4]),
    );
  }

  @protected
  Zone dco_decode_zone(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Zone.values[raw as int];
  }

  @protected
  ZonePrototypeDto dco_decode_zone_prototype_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ZonePrototypeDto(
      id: dco_decode_String(arr[0]),
      label: dco_decode_String(arr[1]),
      centroid: dco_decode_list_prim_f_32_strict(arr[2]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DspEvent sse_decode_box_autoadd_dsp_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_dsp_event(deserializer));
  }

  @protected
  EnrollRejectReason sse_decode_box_autoadd_enroll_reject_reason(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_enroll_reject_reason(deserializer));
  }

  @protected
  WaveformFrame sse_decode_box_autoadd_waveform_frame(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_waveform_frame(deserializer));
  }

  @protected
  DspEvent sse_decode_dsp_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_eventId = sse_decode_u_64(deserializer);
    var var_timestampMs = sse_decode_u_64(deserializer);
    var var_kind = sse_decode_dsp_event_kind(deserializer);
    var var_mfcc = sse_decode_list_prim_f_32_strict(deserializer);
    var var_spectralCentroidHz = sse_decode_f_32(deserializer);
    var var_spectralRolloffHz = sse_decode_f_32(deserializer);
    var var_spectralFlatness = sse_decode_f_32(deserializer);
    var var_subBandEnergy = sse_decode_list_prim_f_32_strict(deserializer);
    var var_rms = sse_decode_f_32(deserializer);
    var var_crestFactor = sse_decode_f_32(deserializer);
    var var_zone = sse_decode_zone(deserializer);
    var var_angleDeg = sse_decode_f_32(deserializer);
    var var_spatialConfidence = sse_decode_f_32(deserializer);
    var var_smoothedAngleDeg = sse_decode_f_32(deserializer);
    var var_smoothedAngleConfidence = sse_decode_f_32(deserializer);
    var var_zoneLabel = sse_decode_String(deserializer);
    var var_zoneId = sse_decode_String(deserializer);
    var var_zoneConfidence = sse_decode_f_32(deserializer);
    return DspEvent(
      eventId: var_eventId,
      timestampMs: var_timestampMs,
      kind: var_kind,
      mfcc: var_mfcc,
      spectralCentroidHz: var_spectralCentroidHz,
      spectralRolloffHz: var_spectralRolloffHz,
      spectralFlatness: var_spectralFlatness,
      subBandEnergy: var_subBandEnergy,
      rms: var_rms,
      crestFactor: var_crestFactor,
      zone: var_zone,
      angleDeg: var_angleDeg,
      spatialConfidence: var_spatialConfidence,
      smoothedAngleDeg: var_smoothedAngleDeg,
      smoothedAngleConfidence: var_smoothedAngleConfidence,
      zoneLabel: var_zoneLabel,
      zoneId: var_zoneId,
      zoneConfidence: var_zoneConfidence,
    );
  }

  @protected
  DspEventKind sse_decode_dsp_event_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return DspEventKind.values[inner];
  }

  @protected
  EnrollClipReport sse_decode_enroll_clip_report(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_accepted = sse_decode_bool(deserializer);
    var var_rejectReason = sse_decode_opt_box_autoadd_enroll_reject_reason(
      deserializer,
    );
    var var_durationMs = sse_decode_u_32(deserializer);
    var var_peakDbfs = sse_decode_f_32(deserializer);
    var var_rmsDbfs = sse_decode_f_32(deserializer);
    var var_noiseFloorDbfs = sse_decode_f_32(deserializer);
    var var_snrDb = sse_decode_f_32(deserializer);
    var var_activeRatio = sse_decode_f_32(deserializer);
    var var_clippingRatio = sse_decode_f_32(deserializer);
    var var_zcr = sse_decode_f_32(deserializer);
    return EnrollClipReport(
      accepted: var_accepted,
      rejectReason: var_rejectReason,
      durationMs: var_durationMs,
      peakDbfs: var_peakDbfs,
      rmsDbfs: var_rmsDbfs,
      noiseFloorDbfs: var_noiseFloorDbfs,
      snrDb: var_snrDb,
      activeRatio: var_activeRatio,
      clippingRatio: var_clippingRatio,
      zcr: var_zcr,
    );
  }

  @protected
  EnrollRejectReason sse_decode_enroll_reject_reason(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return EnrollRejectReason.values[inner];
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt16();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<Float32List> sse_decode_list_list_prim_f_32_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Float32List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_f_32_strict(deserializer));
    }
    return ans_;
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_i_16_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt16List(len_);
  }

  @protected
  Int16List sse_decode_list_prim_i_16_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt16List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ZonePrototypeDto> sse_decode_list_zone_prototype_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ZonePrototypeDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_zone_prototype_dto(deserializer));
    }
    return ans_;
  }

  @protected
  DspEvent? sse_decode_opt_box_autoadd_dsp_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_dsp_event(deserializer));
    } else {
      return null;
    }
  }

  @protected
  EnrollRejectReason? sse_decode_opt_box_autoadd_enroll_reject_reason(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_enroll_reject_reason(deserializer));
    } else {
      return null;
    }
  }

  @protected
  WaveformFrame? sse_decode_opt_box_autoadd_waveform_frame(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_waveform_frame(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SessionPaths sse_decode_session_paths(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_wavPath = sse_decode_String(deserializer);
    var var_imuPath = sse_decode_String(deserializer);
    return SessionPaths(wavPath: var_wavPath, imuPath: var_imuPath);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  WaveformFrame sse_decode_waveform_frame(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_timestampMs = sse_decode_u_64(deserializer);
    var var_left = sse_decode_list_prim_i_16_strict(deserializer);
    var var_right = sse_decode_list_prim_i_16_strict(deserializer);
    var var_peak = sse_decode_i_16(deserializer);
    var var_ringOccupancy = sse_decode_u_32(deserializer);
    return WaveformFrame(
      timestampMs: var_timestampMs,
      left: var_left,
      right: var_right,
      peak: var_peak,
      ringOccupancy: var_ringOccupancy,
    );
  }

  @protected
  Zone sse_decode_zone(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return Zone.values[inner];
  }

  @protected
  ZonePrototypeDto sse_decode_zone_prototype_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_centroid = sse_decode_list_prim_f_32_strict(deserializer);
    return ZonePrototypeDto(
      id: var_id,
      label: var_label,
      centroid: var_centroid,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_dsp_event(
    DspEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_dsp_event(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_enroll_reject_reason(
    EnrollRejectReason self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_enroll_reject_reason(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_waveform_frame(
    WaveformFrame self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_waveform_frame(self, serializer);
  }

  @protected
  void sse_encode_dsp_event(DspEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.eventId, serializer);
    sse_encode_u_64(self.timestampMs, serializer);
    sse_encode_dsp_event_kind(self.kind, serializer);
    sse_encode_list_prim_f_32_strict(self.mfcc, serializer);
    sse_encode_f_32(self.spectralCentroidHz, serializer);
    sse_encode_f_32(self.spectralRolloffHz, serializer);
    sse_encode_f_32(self.spectralFlatness, serializer);
    sse_encode_list_prim_f_32_strict(self.subBandEnergy, serializer);
    sse_encode_f_32(self.rms, serializer);
    sse_encode_f_32(self.crestFactor, serializer);
    sse_encode_zone(self.zone, serializer);
    sse_encode_f_32(self.angleDeg, serializer);
    sse_encode_f_32(self.spatialConfidence, serializer);
    sse_encode_f_32(self.smoothedAngleDeg, serializer);
    sse_encode_f_32(self.smoothedAngleConfidence, serializer);
    sse_encode_String(self.zoneLabel, serializer);
    sse_encode_String(self.zoneId, serializer);
    sse_encode_f_32(self.zoneConfidence, serializer);
  }

  @protected
  void sse_encode_dsp_event_kind(DspEventKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_enroll_clip_report(
    EnrollClipReport self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.accepted, serializer);
    sse_encode_opt_box_autoadd_enroll_reject_reason(
      self.rejectReason,
      serializer,
    );
    sse_encode_u_32(self.durationMs, serializer);
    sse_encode_f_32(self.peakDbfs, serializer);
    sse_encode_f_32(self.rmsDbfs, serializer);
    sse_encode_f_32(self.noiseFloorDbfs, serializer);
    sse_encode_f_32(self.snrDb, serializer);
    sse_encode_f_32(self.activeRatio, serializer);
    sse_encode_f_32(self.clippingRatio, serializer);
    sse_encode_f_32(self.zcr, serializer);
  }

  @protected
  void sse_encode_enroll_reject_reason(
    EnrollRejectReason self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt16(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_list_prim_f_32_strict(
    List<Float32List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_f_32_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_i_16_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt16List(
      self is Int16List ? self : Int16List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_i_16_strict(
    Int16List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt16List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_zone_prototype_dto(
    List<ZonePrototypeDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_zone_prototype_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_dsp_event(
    DspEvent? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_dsp_event(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_enroll_reject_reason(
    EnrollRejectReason? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_enroll_reject_reason(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_waveform_frame(
    WaveformFrame? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_waveform_frame(self, serializer);
    }
  }

  @protected
  void sse_encode_session_paths(SessionPaths self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.wavPath, serializer);
    sse_encode_String(self.imuPath, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_waveform_frame(WaveformFrame self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.timestampMs, serializer);
    sse_encode_list_prim_i_16_strict(self.left, serializer);
    sse_encode_list_prim_i_16_strict(self.right, serializer);
    sse_encode_i_16(self.peak, serializer);
    sse_encode_u_32(self.ringOccupancy, serializer);
  }

  @protected
  void sse_encode_zone(Zone self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_zone_prototype_dto(
    ZonePrototypeDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_list_prim_f_32_strict(self.centroid, serializer);
  }
}
