// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/audio_stream.dart';
import 'api/dsp_pipeline.dart';
import 'api/enrollment.dart';
import 'api/session.dart';
import 'api/zone.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DspEvent dco_decode_box_autoadd_dsp_event(dynamic raw);

  @protected
  EnrollRejectReason dco_decode_box_autoadd_enroll_reject_reason(dynamic raw);

  @protected
  WaveformFrame dco_decode_box_autoadd_waveform_frame(dynamic raw);

  @protected
  DspEvent dco_decode_dsp_event(dynamic raw);

  @protected
  DspEventKind dco_decode_dsp_event_kind(dynamic raw);

  @protected
  EnrollClipReport dco_decode_enroll_clip_report(dynamic raw);

  @protected
  EnrollRejectReason dco_decode_enroll_reject_reason(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  int dco_decode_i_16(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<Float32List> dco_decode_list_list_prim_f_32_strict(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_i_16_loose(dynamic raw);

  @protected
  Int16List dco_decode_list_prim_i_16_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ZonePrototypeDto> dco_decode_list_zone_prototype_dto(dynamic raw);

  @protected
  DspEvent? dco_decode_opt_box_autoadd_dsp_event(dynamic raw);

  @protected
  EnrollRejectReason? dco_decode_opt_box_autoadd_enroll_reject_reason(
    dynamic raw,
  );

  @protected
  WaveformFrame? dco_decode_opt_box_autoadd_waveform_frame(dynamic raw);

  @protected
  SessionPaths dco_decode_session_paths(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  WaveformFrame dco_decode_waveform_frame(dynamic raw);

  @protected
  Zone dco_decode_zone(dynamic raw);

  @protected
  ZonePrototypeDto dco_decode_zone_prototype_dto(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DspEvent sse_decode_box_autoadd_dsp_event(SseDeserializer deserializer);

  @protected
  EnrollRejectReason sse_decode_box_autoadd_enroll_reject_reason(
    SseDeserializer deserializer,
  );

  @protected
  WaveformFrame sse_decode_box_autoadd_waveform_frame(
    SseDeserializer deserializer,
  );

  @protected
  DspEvent sse_decode_dsp_event(SseDeserializer deserializer);

  @protected
  DspEventKind sse_decode_dsp_event_kind(SseDeserializer deserializer);

  @protected
  EnrollClipReport sse_decode_enroll_clip_report(SseDeserializer deserializer);

  @protected
  EnrollRejectReason sse_decode_enroll_reject_reason(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  int sse_decode_i_16(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<Float32List> sse_decode_list_list_prim_f_32_strict(
    SseDeserializer deserializer,
  );

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_i_16_loose(SseDeserializer deserializer);

  @protected
  Int16List sse_decode_list_prim_i_16_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ZonePrototypeDto> sse_decode_list_zone_prototype_dto(
    SseDeserializer deserializer,
  );

  @protected
  DspEvent? sse_decode_opt_box_autoadd_dsp_event(SseDeserializer deserializer);

  @protected
  EnrollRejectReason? sse_decode_opt_box_autoadd_enroll_reject_reason(
    SseDeserializer deserializer,
  );

  @protected
  WaveformFrame? sse_decode_opt_box_autoadd_waveform_frame(
    SseDeserializer deserializer,
  );

  @protected
  SessionPaths sse_decode_session_paths(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  WaveformFrame sse_decode_waveform_frame(SseDeserializer deserializer);

  @protected
  Zone sse_decode_zone(SseDeserializer deserializer);

  @protected
  ZonePrototypeDto sse_decode_zone_prototype_dto(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_dsp_event(
    DspEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_enroll_reject_reason(
    EnrollRejectReason self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_waveform_frame(
    WaveformFrame self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dsp_event(DspEvent self, SseSerializer serializer);

  @protected
  void sse_encode_dsp_event_kind(DspEventKind self, SseSerializer serializer);

  @protected
  void sse_encode_enroll_clip_report(
    EnrollClipReport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_enroll_reject_reason(
    EnrollRejectReason self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_prim_f_32_strict(
    List<Float32List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_16_loose(
    List<int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_16_strict(
    Int16List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_zone_prototype_dto(
    List<ZonePrototypeDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_dsp_event(
    DspEvent? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_enroll_reject_reason(
    EnrollRejectReason? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_waveform_frame(
    WaveformFrame? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_session_paths(SessionPaths self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_waveform_frame(WaveformFrame self, SseSerializer serializer);

  @protected
  void sse_encode_zone(Zone self, SseSerializer serializer);

  @protected
  void sse_encode_zone_prototype_dto(
    ZonePrototypeDto self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
