// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/audio_stream.dart';
import 'api/dsp_pipeline.dart';
import 'api/session.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1423800464;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'prism_dsp',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiSessionAppendImuSample({
    required BigInt tsNs,
    required double ax,
    required double ay,
    required double az,
    required double gx,
    required double gy,
    required double gz,
  });

  DspEvent? crateApiDspPipelineNextDspEvent();

  WaveformFrame? crateApiAudioStreamNextWaveformFrame();

  int crateApiAudioStreamRingOccupancy();

  void crateApiDspPipelineStartDsp();

  SessionPaths crateApiSessionStartSession({
    required String documentsDir,
    required String tsLabel,
  });

  void crateApiDspPipelineStopDsp();

  SessionPaths crateApiSessionStopSession();

  Int16List crateApiDspPipelineTakeEventAudio16K({required BigInt eventId});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiSessionAppendImuSample({
    required BigInt tsNs,
    required double ax,
    required double ay,
    required double az,
    required double gx,
    required double gy,
    required double gz,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(tsNs, serializer);
          sse_encode_f_32(ax, serializer);
          sse_encode_f_32(ay, serializer);
          sse_encode_f_32(az, serializer);
          sse_encode_f_32(gx, serializer);
          sse_encode_f_32(gy, serializer);
          sse_encode_f_32(gz, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSessionAppendImuSampleConstMeta,
        argValues: [tsNs, ax, ay, az, gx, gy, gz],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionAppendImuSampleConstMeta =>
      const TaskConstMeta(
        debugName: "append_imu_sample",
        argNames: ["tsNs", "ax", "ay", "az", "gx", "gy", "gz"],
      );

  @override
  DspEvent? crateApiDspPipelineNextDspEvent() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_dsp_event,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDspPipelineNextDspEventConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDspPipelineNextDspEventConstMeta =>
      const TaskConstMeta(debugName: "next_dsp_event", argNames: []);

  @override
  WaveformFrame? crateApiAudioStreamNextWaveformFrame() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_waveform_frame,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioStreamNextWaveformFrameConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioStreamNextWaveformFrameConstMeta =>
      const TaskConstMeta(debugName: "next_waveform_frame", argNames: []);

  @override
  int crateApiAudioStreamRingOccupancy() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioStreamRingOccupancyConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioStreamRingOccupancyConstMeta =>
      const TaskConstMeta(debugName: "ring_occupancy", argNames: []);

  @override
  void crateApiDspPipelineStartDsp() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDspPipelineStartDspConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDspPipelineStartDspConstMeta =>
      const TaskConstMeta(debugName: "start_dsp", argNames: []);

  @override
  SessionPaths crateApiSessionStartSession({
    required String documentsDir,
    required String tsLabel,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(documentsDir, serializer);
          sse_encode_String(tsLabel, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_session_paths,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSessionStartSessionConstMeta,
        argValues: [documentsDir, tsLabel],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionStartSessionConstMeta =>
      const TaskConstMeta(
        debugName: "start_session",
        argNames: ["documentsDir", "tsLabel"],
      );

  @override
  void crateApiDspPipelineStopDsp() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDspPipelineStopDspConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDspPipelineStopDspConstMeta =>
      const TaskConstMeta(debugName: "stop_dsp", argNames: []);

  @override
  SessionPaths crateApiSessionStopSession() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_session_paths,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSessionStopSessionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionStopSessionConstMeta =>
      const TaskConstMeta(debugName: "stop_session", argNames: []);

  @override
  Int16List crateApiDspPipelineTakeEventAudio16K({required BigInt eventId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(eventId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_i_16_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDspPipelineTakeEventAudio16KConstMeta,
        argValues: [eventId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDspPipelineTakeEventAudio16KConstMeta =>
      const TaskConstMeta(
        debugName: "take_event_audio_16k",
        argNames: ["eventId"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  DspEvent dco_decode_box_autoadd_dsp_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_dsp_event(raw);
  }

  @protected
  WaveformFrame dco_decode_box_autoadd_waveform_frame(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_waveform_frame(raw);
  }

  @protected
  DspEvent dco_decode_dsp_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13)
      throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return DspEvent(
      eventId: dco_decode_u_64(arr[0]),
      timestampMs: dco_decode_u_64(arr[1]),
      kind: dco_decode_dsp_event_kind(arr[2]),
      mfcc: dco_decode_list_prim_f_32_strict(arr[3]),
      spectralCentroidHz: dco_decode_f_32(arr[4]),
      spectralRolloffHz: dco_decode_f_32(arr[5]),
      spectralFlatness: dco_decode_f_32(arr[6]),
      subBandEnergy: dco_decode_list_prim_f_32_strict(arr[7]),
      rms: dco_decode_f_32(arr[8]),
      crestFactor: dco_decode_f_32(arr[9]),
      zone: dco_decode_zone(arr[10]),
      angleDeg: dco_decode_f_32(arr[11]),
      spatialConfidence: dco_decode_f_32(arr[12]),
    );
  }

  @protected
  DspEventKind dco_decode_dsp_event_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DspEventKind.values[raw as int];
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  Int16List dco_decode_list_prim_i_16_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Int16List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  DspEvent? dco_decode_opt_box_autoadd_dsp_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_dsp_event(raw);
  }

  @protected
  WaveformFrame? dco_decode_opt_box_autoadd_waveform_frame(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_waveform_frame(raw);
  }

  @protected
  SessionPaths dco_decode_session_paths(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SessionPaths(
      wavPath: dco_decode_String(arr[0]),
      imuPath: dco_decode_String(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  WaveformFrame dco_decode_waveform_frame(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return WaveformFrame(
      timestampMs: dco_decode_u_64(arr[0]),
      left: dco_decode_list_prim_i_16_strict(arr[1]),
      right: dco_decode_list_prim_i_16_strict(arr[2]),
      peak: dco_decode_i_16(arr[3]),
      ringOccupancy: dco_decode_u_32(arr[4]),
    );
  }

  @protected
  Zone dco_decode_zone(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Zone.values[raw as int];
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  DspEvent sse_decode_box_autoadd_dsp_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_dsp_event(deserializer));
  }

  @protected
  WaveformFrame sse_decode_box_autoadd_waveform_frame(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_waveform_frame(deserializer));
  }

  @protected
  DspEvent sse_decode_dsp_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_eventId = sse_decode_u_64(deserializer);
    var var_timestampMs = sse_decode_u_64(deserializer);
    var var_kind = sse_decode_dsp_event_kind(deserializer);
    var var_mfcc = sse_decode_list_prim_f_32_strict(deserializer);
    var var_spectralCentroidHz = sse_decode_f_32(deserializer);
    var var_spectralRolloffHz = sse_decode_f_32(deserializer);
    var var_spectralFlatness = sse_decode_f_32(deserializer);
    var var_subBandEnergy = sse_decode_list_prim_f_32_strict(deserializer);
    var var_rms = sse_decode_f_32(deserializer);
    var var_crestFactor = sse_decode_f_32(deserializer);
    var var_zone = sse_decode_zone(deserializer);
    var var_angleDeg = sse_decode_f_32(deserializer);
    var var_spatialConfidence = sse_decode_f_32(deserializer);
    return DspEvent(
      eventId: var_eventId,
      timestampMs: var_timestampMs,
      kind: var_kind,
      mfcc: var_mfcc,
      spectralCentroidHz: var_spectralCentroidHz,
      spectralRolloffHz: var_spectralRolloffHz,
      spectralFlatness: var_spectralFlatness,
      subBandEnergy: var_subBandEnergy,
      rms: var_rms,
      crestFactor: var_crestFactor,
      zone: var_zone,
      angleDeg: var_angleDeg,
      spatialConfidence: var_spatialConfidence,
    );
  }

  @protected
  DspEventKind sse_decode_dsp_event_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return DspEventKind.values[inner];
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt16();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Int16List sse_decode_list_prim_i_16_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt16List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  DspEvent? sse_decode_opt_box_autoadd_dsp_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_dsp_event(deserializer));
    } else {
      return null;
    }
  }

  @protected
  WaveformFrame? sse_decode_opt_box_autoadd_waveform_frame(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_waveform_frame(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SessionPaths sse_decode_session_paths(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_wavPath = sse_decode_String(deserializer);
    var var_imuPath = sse_decode_String(deserializer);
    return SessionPaths(wavPath: var_wavPath, imuPath: var_imuPath);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  WaveformFrame sse_decode_waveform_frame(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_timestampMs = sse_decode_u_64(deserializer);
    var var_left = sse_decode_list_prim_i_16_strict(deserializer);
    var var_right = sse_decode_list_prim_i_16_strict(deserializer);
    var var_peak = sse_decode_i_16(deserializer);
    var var_ringOccupancy = sse_decode_u_32(deserializer);
    return WaveformFrame(
      timestampMs: var_timestampMs,
      left: var_left,
      right: var_right,
      peak: var_peak,
      ringOccupancy: var_ringOccupancy,
    );
  }

  @protected
  Zone sse_decode_zone(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return Zone.values[inner];
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_box_autoadd_dsp_event(
    DspEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_dsp_event(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_waveform_frame(
    WaveformFrame self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_waveform_frame(self, serializer);
  }

  @protected
  void sse_encode_dsp_event(DspEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.eventId, serializer);
    sse_encode_u_64(self.timestampMs, serializer);
    sse_encode_dsp_event_kind(self.kind, serializer);
    sse_encode_list_prim_f_32_strict(self.mfcc, serializer);
    sse_encode_f_32(self.spectralCentroidHz, serializer);
    sse_encode_f_32(self.spectralRolloffHz, serializer);
    sse_encode_f_32(self.spectralFlatness, serializer);
    sse_encode_list_prim_f_32_strict(self.subBandEnergy, serializer);
    sse_encode_f_32(self.rms, serializer);
    sse_encode_f_32(self.crestFactor, serializer);
    sse_encode_zone(self.zone, serializer);
    sse_encode_f_32(self.angleDeg, serializer);
    sse_encode_f_32(self.spatialConfidence, serializer);
  }

  @protected
  void sse_encode_dsp_event_kind(DspEventKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt16(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_i_16_strict(
    Int16List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt16List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_box_autoadd_dsp_event(
    DspEvent? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_dsp_event(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_waveform_frame(
    WaveformFrame? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_waveform_frame(self, serializer);
    }
  }

  @protected
  void sse_encode_session_paths(SessionPaths self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.wavPath, serializer);
    sse_encode_String(self.imuPath, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_waveform_frame(WaveformFrame self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.timestampMs, serializer);
    sse_encode_list_prim_i_16_strict(self.left, serializer);
    sse_encode_list_prim_i_16_strict(self.right, serializer);
    sse_encode_i_16(self.peak, serializer);
    sse_encode_u_32(self.ringOccupancy, serializer);
  }

  @protected
  void sse_encode_zone(Zone self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
