// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `scratch`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Pop up to ~33 ms of interleaved samples and return a decimated waveform frame.
/// Returns None when the ring is empty (fewer than 2 samples available).
WaveformFrame? nextWaveformFrame() =>
    RustLib.instance.api.crateApiAudioStreamNextWaveformFrame();

int ringOccupancy() => RustLib.instance.api.crateApiAudioStreamRingOccupancy();

/// One waveform frame for the UI scope.
class WaveformFrame {
  final BigInt timestampMs;

  /// Decimated left channel, length ≤ `WAVEFORM_FRAME_LEN`.
  final Int16List left;

  /// Decimated right channel, length ≤ `WAVEFORM_FRAME_LEN`.
  final Int16List right;

  /// Peak absolute amplitude (0..32767) seen in this frame across both channels.
  final int peak;

  /// Samples available in the ring buffer right now (interleaved count).
  final int ringOccupancy;

  const WaveformFrame({
    required this.timestampMs,
    required this.left,
    required this.right,
    required this.peak,
    required this.ringOccupancy,
  });

  @override
  int get hashCode =>
      timestampMs.hashCode ^
      left.hashCode ^
      right.hashCode ^
      peak.hashCode ^
      ringOccupancy.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WaveformFrame &&
          runtimeType == other.runtimeType &&
          timestampMs == other.timestampMs &&
          left == other.left &&
          right == other.right &&
          peak == other.peak &&
          ringOccupancy == other.ringOccupancy;
}
