// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_event`, `channel`, `compute_phase3_extras`, `compute_spatial`, `compute_zone_feature`, `dsp_loop`, `emit_event`, `finalize_captures`, `queue_event`, `segments`, `start_instant`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `from`

void startDsp() => RustLib.instance.api.crateApiDspPipelineStartDsp();

void stopDsp() => RustLib.instance.api.crateApiDspPipelineStopDsp();

DspEvent? nextDspEvent() =>
    RustLib.instance.api.crateApiDspPipelineNextDspEvent();

/// Pop the cached 16 kHz mono audio segment around an event.
/// Returns interleaved Int16 samples; empty if the segment has expired or never existed.
Int16List takeEventAudio16K({required BigInt eventId}) =>
    RustLib.instance.api.crateApiDspPipelineTakeEventAudio16K(eventId: eventId);

class DspEvent {
  final BigInt eventId;
  final BigInt timestampMs;
  final DspEventKind kind;
  final Float32List mfcc;
  final double spectralCentroidHz;
  final double spectralRolloffHz;
  final double spectralFlatness;
  final Float32List subBandEnergy;
  final double rms;
  final double crestFactor;
  final Zone zone;
  final double angleDeg;
  final double spatialConfidence;

  /// Phase 3: Kalman-smoothed angle. 0 when no fresh measurement and
  /// no prior state — use `smoothed_angle_confidence == 0.0` as the
  /// gate, not `angle == 0.0`, since the genuine center is 0°.
  final double smoothedAngleDeg;

  /// 0..1, derived from posterior variance. Drops as the filter coasts
  /// without measurement updates.
  final double smoothedAngleConfidence;

  /// Phase 3: best-matching enrolled room. Empty string when no
  /// prototype crossed the confidence/margin floor.
  final String zoneLabel;
  final String zoneId;
  final double zoneConfidence;

  const DspEvent({
    required this.eventId,
    required this.timestampMs,
    required this.kind,
    required this.mfcc,
    required this.spectralCentroidHz,
    required this.spectralRolloffHz,
    required this.spectralFlatness,
    required this.subBandEnergy,
    required this.rms,
    required this.crestFactor,
    required this.zone,
    required this.angleDeg,
    required this.spatialConfidence,
    required this.smoothedAngleDeg,
    required this.smoothedAngleConfidence,
    required this.zoneLabel,
    required this.zoneId,
    required this.zoneConfidence,
  });

  @override
  int get hashCode =>
      eventId.hashCode ^
      timestampMs.hashCode ^
      kind.hashCode ^
      mfcc.hashCode ^
      spectralCentroidHz.hashCode ^
      spectralRolloffHz.hashCode ^
      spectralFlatness.hashCode ^
      subBandEnergy.hashCode ^
      rms.hashCode ^
      crestFactor.hashCode ^
      zone.hashCode ^
      angleDeg.hashCode ^
      spatialConfidence.hashCode ^
      smoothedAngleDeg.hashCode ^
      smoothedAngleConfidence.hashCode ^
      zoneLabel.hashCode ^
      zoneId.hashCode ^
      zoneConfidence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DspEvent &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId &&
          timestampMs == other.timestampMs &&
          kind == other.kind &&
          mfcc == other.mfcc &&
          spectralCentroidHz == other.spectralCentroidHz &&
          spectralRolloffHz == other.spectralRolloffHz &&
          spectralFlatness == other.spectralFlatness &&
          subBandEnergy == other.subBandEnergy &&
          rms == other.rms &&
          crestFactor == other.crestFactor &&
          zone == other.zone &&
          angleDeg == other.angleDeg &&
          spatialConfidence == other.spatialConfidence &&
          smoothedAngleDeg == other.smoothedAngleDeg &&
          smoothedAngleConfidence == other.smoothedAngleConfidence &&
          zoneLabel == other.zoneLabel &&
          zoneId == other.zoneId &&
          zoneConfidence == other.zoneConfidence;
}

enum DspEventKind { vadStart, vadEnd, onset, periodicSnapshot }

enum Zone { left, center, right, unknown }
