// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_parts`, `pipeline_tap_push`, `tap`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EnrollmentTap`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `from`

/// Analyze a 16 kHz mono i16 clip with default enrollment gates.
Future<EnrollClipReport> analyzeEnrollmentClip16K({
  required List<int> samples,
}) => RustLib.instance.api.crateApiEnrollmentAnalyzeEnrollmentClip16K(
  samples: samples,
);

/// Begin a fresh enrollment recording. Idempotent: calling twice resets.
/// [max_duration_ms] caps memory; once the cap is hit the tap stops accepting
/// new samples but keeps everything captured so far.
Future<void> enrollRecorderStart({required int maxDurationMs}) => RustLib
    .instance
    .api
    .crateApiEnrollmentEnrollRecorderStart(maxDurationMs: maxDurationMs);

/// Stop recording and return the captured audio as 16 kHz mono i16.
/// Uses a stride-and-average resampler (3:1 at 48→16 kHz) — same scheme as
/// the segment-capture path in `dsp_pipeline` so any aliasing artifacts
/// are consistent across the codebase.
Future<Int16List> enrollRecorderStopTake() =>
    RustLib.instance.api.crateApiEnrollmentEnrollRecorderStopTake();

Future<EnrollClipReport> analyzeEnrollmentClip16KTuned({
  required List<int> samples,
  required int minDurationMs,
  required int maxDurationMs,
  required double minSnrDb,
  required double minActiveRatio,
  required double maxClippingRatio,
  required double minPeakDbfs,
}) => RustLib.instance.api.crateApiEnrollmentAnalyzeEnrollmentClip16KTuned(
  samples: samples,
  minDurationMs: minDurationMs,
  maxDurationMs: maxDurationMs,
  minSnrDb: minSnrDb,
  minActiveRatio: minActiveRatio,
  maxClippingRatio: maxClippingRatio,
  minPeakDbfs: minPeakDbfs,
);

class EnrollClipReport {
  final bool accepted;
  final EnrollRejectReason? rejectReason;
  final int durationMs;
  final double peakDbfs;
  final double rmsDbfs;
  final double noiseFloorDbfs;
  final double snrDb;
  final double activeRatio;
  final double clippingRatio;
  final double zcr;

  const EnrollClipReport({
    required this.accepted,
    this.rejectReason,
    required this.durationMs,
    required this.peakDbfs,
    required this.rmsDbfs,
    required this.noiseFloorDbfs,
    required this.snrDb,
    required this.activeRatio,
    required this.clippingRatio,
    required this.zcr,
  });

  @override
  int get hashCode =>
      accepted.hashCode ^
      rejectReason.hashCode ^
      durationMs.hashCode ^
      peakDbfs.hashCode ^
      rmsDbfs.hashCode ^
      noiseFloorDbfs.hashCode ^
      snrDb.hashCode ^
      activeRatio.hashCode ^
      clippingRatio.hashCode ^
      zcr.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EnrollClipReport &&
          runtimeType == other.runtimeType &&
          accepted == other.accepted &&
          rejectReason == other.rejectReason &&
          durationMs == other.durationMs &&
          peakDbfs == other.peakDbfs &&
          rmsDbfs == other.rmsDbfs &&
          noiseFloorDbfs == other.noiseFloorDbfs &&
          snrDb == other.snrDb &&
          activeRatio == other.activeRatio &&
          clippingRatio == other.clippingRatio &&
          zcr == other.zcr;
}

enum EnrollRejectReason {
  tooShort,
  tooLong,
  tooQuiet,
  tooNoisy,
  clipping,
  noSignal,
}
