// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `state`, `wav_drain_loop`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SessionState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

SessionPaths startSession({
  required String documentsDir,
  required String tsLabel,
}) => RustLib.instance.api.crateApiSessionStartSession(
  documentsDir: documentsDir,
  tsLabel: tsLabel,
);

SessionPaths stopSession() => RustLib.instance.api.crateApiSessionStopSession();

/// Called from the native IMU sample callback. Appends one row to the CSV.
Future<void> appendImuSample({
  required BigInt tsNs,
  required double ax,
  required double ay,
  required double az,
  required double gx,
  required double gy,
  required double gz,
}) => RustLib.instance.api.crateApiSessionAppendImuSample(
  tsNs: tsNs,
  ax: ax,
  ay: ay,
  az: az,
  gx: gx,
  gy: gy,
  gz: gz,
);

class SessionPaths {
  final String wavPath;
  final String imuPath;

  const SessionPaths({required this.wavPath, required this.imuPath});

  @override
  int get hashCode => wavPath.hashCode ^ imuPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionPaths &&
          runtimeType == other.runtimeType &&
          wavPath == other.wavPath &&
          imuPath == other.imuPath;
}
