// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `prototypes`, `snapshot_prototypes`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Read by Dart to verify against the dimension it stores.
int zoneFeatureDim() => RustLib.instance.api.crateApiZoneZoneFeatureDim();

/// Replace the active prototype set. Returns the accepted count.
/// Prototypes with the wrong centroid length are silently dropped — log
/// the count mismatch on the Dart side if it matters.
int zoneSetPrototypes({required List<ZonePrototypeDto> items}) =>
    RustLib.instance.api.crateApiZoneZoneSetPrototypes(items: items);

void zoneClearPrototypes() =>
    RustLib.instance.api.crateApiZoneZoneClearPrototypes();

int zonePrototypeCount() =>
    RustLib.instance.api.crateApiZoneZonePrototypeCount();

/// Compute the 21-D acoustic fingerprint of a mono 16 kHz audio buffer.
/// Used at enrollment time: Dart records ~30 s of ambient, passes it here,
/// receives the centroid, persists it in the sidecar, and pushes the new
/// prototype set back via `zone_set_prototypes`.
///
/// The buffer SHOULD be at least 4096 samples (one STFT window at 16 kHz).
/// Shorter inputs return a zero vector — Dart should validate length and
/// surface a "recording too short" error before calling.
Float32List zoneComputeFeature({required List<int> samples16KMono}) => RustLib
    .instance
    .api
    .crateApiZoneZoneComputeFeature(samples16KMono: samples16KMono);

/// Aggregate a batch of per-window feature vectors into a single
/// L2-normalized centroid. Optional — Dart can also just average and
/// renormalize itself, but exposing it avoids float-precision drift
/// between Dart and Rust math.
Float32List zoneCentroidFromFeatures({required List<Float32List> features}) =>
    RustLib.instance.api.crateApiZoneZoneCentroidFromFeatures(
      features: features,
    );

/// Dart-facing prototype DTO. Uses a `Vec` of `f32` (rather than a fixed-size
/// array) because flutter_rust_bridge does not auto-generate Dart for raw
/// Rust arrays. The vector MUST have length `ZONE_FEATURE_DIM_OUT` (= 21);
/// other lengths are rejected at `zone_set_prototypes` time.
class ZonePrototypeDto {
  final String id;
  final String label;
  final Float32List centroid;

  const ZonePrototypeDto({
    required this.id,
    required this.label,
    required this.centroid,
  });

  @override
  int get hashCode => id.hashCode ^ label.hashCode ^ centroid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ZonePrototypeDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          centroid == other.centroid;
}
